blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

mailing_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('client/', include('client.urls', namespace='client')),
                  path('mailing/', include('newletter.urls', namespace='newletter')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import NULLABLE


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(**NULLABLE, upload_to='articles/', verbose_name='Превью')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания публикации')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import DeleteView, UpdateView, DetailView, CreateView, ListView

from blog.models import Blog


# Create your views here.
class BlogListView(LoginRequiredMixin, ListView):
    model = Blog
    extra_context = {
        'title': 'Blog'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['content_manager'] = user.groups.filter(name='content_manager').exists() or user.is_superuser
        return context


class BlogCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'preview')
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Add new article',
    }

    def test_func(self):
        return self.request.user.groups.filter(name='content_manager').exists() or self.request.user.is_superuser


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    extra_context = {
        'title': 'View blog article'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview')
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Edit article',
    }

    def test_func(self):
        return self.request.user.groups.filter(name='content_manager').exists() or self.request.user.is_superuser


class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Delete article',
    }

    def test_func(self):
        return self.request.user.groups.filter(name='content_manager').exists() or self.request.user.is_superuser

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить статью "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger"
                                    title="УДАЛИТЬ ПРЯМ ПОЛНОСТЬЮ">Удалить
                            </button>
                            <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.title }}
                        </h3>
                    </div>
                    <div class="card">
                        {% if object.preview %}
                            <img src="/media/{{ object.preview }}" class="card-img-top" alt="" height="400">
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.content }}
                        </p>
                    </div>
                    <div class="card-footer">
                        Просмотров: {{ object.views_count }}
                    </div>
                    <div class="card-footer">
                        Дата публикации: {{ object.created_at }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.title.label }}">Заголовок</label><br/>
                            {{ form.title }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.content.label }}">Содержание</label><br/>
                            {{ form.content }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.preview.label }}">Картинка статьи</label><br/>
                            {{ form.preview }}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                                Сохранить статью
                            {% else %}
                                Создать статью
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
        <p class="lead">Статьи для продвижения сайта</p>

    </div>
    {% if content_manager %}
        <div class="col-4 mb-5">
            <a class="btn btn-outline-primary" href="{% url 'blog:blog_create' %}">Добавить статью</a>
        </div>
    {% endif %}

    <div class="d-flex flex-wrap">
        {% for object in object_list %}
            <div class="card m-2" style="width: 18rem;">
                {% if object.preview %}
                    <img src="/media/{{ object.preview }}" class="card-img-top" alt="" height="150">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.content|truncatechars:20 }}</p>
                    <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-primary">Читать полностью</a><br/>
                    {% if content_manager %}<br/>
                        <a href="{% url 'blog:blog_update' object.pk %}" type="button" class="btn btn-secondary">Редактировать</a>
                        <a href="{% url 'blog:blog_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}