blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

client/urls.py
from django.urls import path

from client.apps import ClientConfig
from client.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView

app_name = ClientConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_view'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/edit/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
]

mailing_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('client/', include('client.urls', namespace='client')),
                  path('mailing/', include('newletter.urls', namespace='newletter')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newletter/urls.py
from django.urls import path

from newletter.apps import NewletterConfig
from newletter.views import MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, \
    MessageDeleteView, MailingLogsListView, SettingsListView, SettingCreateView, SettingUpdateView, SettingDeleteView

app_name = NewletterConfig.name

urlpatterns = [
    path('list/', MessageListView.as_view(), name='message_list'),
    path('list/detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('list/create/', MessageCreateView.as_view(), name='message_create'),
    path('list/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('list/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('logs/', MailingLogsListView.as_view(), name='report_list'),
    path('settings/list', SettingsListView.as_view(), name='setting_list'),
    path('settings/create', SettingCreateView.as_view(), name='setting_create'),
    path('settings/update/<int:pk>', SettingUpdateView.as_view(), name='setting_update'),
    path('settings/delete/<int:pk>', SettingDeleteView.as_view(), name='setting_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, logout_view, RegisterView, UserUpdateView, UserVerifyView, \
    ManagerView, UserListView, DisableUserView, DisableMessageView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verify/<int:pk>/', UserVerifyView.as_view(), name='verification'),
    path('profile_edit/', UserUpdateView.as_view(), name='profile_edit'),
    path('profile_delete/<int:pk>/', UserDeleteView.as_view(), name='profile_delete'),
    path('manager/', ManagerView.as_view(), name='manager_profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('disable_user/<int:pk>/', DisableUserView.as_view(), name='user_disable'),
    path('disable_message/<int:pk>/', DisableMessageView.as_view(), name='message_disable'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': 'True', 'null': 'True'}


# Create your models here.
class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='email', unique=True)
    avatar = models.ImageField(verbose_name='avatar', **NULLABLE)
    phone = models.CharField(verbose_name='phone', max_length=30, **NULLABLE)
    country = models.CharField(verbose_name='country', max_length=40, **NULLABLE)
    is_active = models.BooleanField(verbose_name='is_active', default=False)

    verify_code = models.CharField(default=0, verbose_name='код верификации')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}),
        label='Пароль')
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите пароль'}),
        label='Повторите пароль')

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите email'}),
        }


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar', 'phone', 'country',)

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилию'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Телефон'}),
            'country': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Страна'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class VerificationForm(forms.Form):
    verify_code = forms.CharField(max_length=12, label='Введите код верификации')

users/views.py
import random

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth import logout
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, View, ListView, DeleteView

from newletter.models import Message
from users.forms import UserRegisterForm, UserForm, VerificationForm
from users.models import User


# Create your views here.
class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Log in to account'
    }

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Вы успешно авторизовались')
        return response


def logout_view(request):
    logout(request)
    return redirect('main:main_window')


class RegisterView(CreateView):
    model = User
    extra_context = {
        'title': 'Registration'
    }
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        generate_code = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        user.verify_code = generate_code
        user.save()

        send_mail(
            subject='Код верификации',
            message=f'Пожалуйста, для вашей верификации и активации аккаунта введите код: {generate_code}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return redirect(reverse('users:verification', kwargs={'pk': user.pk}))


class UserVerifyView(View):
    template_name = 'users/verification.html'
    extra_context = {
        'title': 'Verification'
    }

    def get(self, request, *args, **kwargs):
        form = VerificationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = VerificationForm(request.POST)
        if form.is_valid():
            entered_code = form.cleaned_data['verify_code']
            user_pk = kwargs.get('pk')
            user = get_object_or_404(User, pk=user_pk)

            if entered_code == user.verify_code:
                user.is_active = True
                user.save()
                messages.success(request, 'Аккаунт активирован')
                return redirect(reverse('users:login'))
            else:
                messages.error(request, 'Неверный код верификации.')

        return render(request, self.template_name, {'form': form})


class UserListView(UserPassesTestMixin, ListView):
    model = User
    extra_context = {
        'title': 'Users'
    }

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser


class UserUpdateView(UpdateView):
    model = User
    extra_context = {
        'title': 'Edit profile'
    }
    success_url = reverse_lazy('users:profile_edit')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('main:main_window')
    extra_context = {
        'title': 'Delete account',
    }


class ManagerView(UserPassesTestMixin, View):
    template_name = 'users/manager.html'

    def get(self, request, *args, **kwargs):
        context = {
            'title': 'Manager account',
        }
        return render(request, self.template_name, context)

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser


class DisableUserView(UserPassesTestMixin, View):
    def get(self, request, pk):
        user = User.objects.get(pk=pk)

        if user.is_active:
            user.is_active = False
        elif not user.is_active:
            user.is_active = True

        user.save()
        return redirect('users:users_list')

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser


class DisableMessageView(UserPassesTestMixin, View):
    def get(self, request, pk):
        message = Message.objects.get(pk=pk)

        if message.is_active:
            message.is_active = False
        elif not message.is_active:
            message.is_active = True

        message.save()
        return redirect('newsletter:message_detail', pk=pk)

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Войдите в аккаунт</h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div>
                                {{ form.as_p }}
                            </div>

                            <button type="submit" class="btn btn-primary">Войти</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/manager.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row justify-content-center">
            <div class="card col-5 mb-2 mx-auto">
                <h6>Все пользователи</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:users_list' %}">Пользователи</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Все рассылки</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'newletter:message_list' %}">К рассылкам</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Логи рассылок</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'newletter:report_list' %}">К логам</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Клиенты сервиса</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'client:client_list' %}">К клиентам</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Перейти в административную панель</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'admin:index' %}">Админка</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Перейти к настройкам рассылки</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'newletter:setting_list' %}">Настройки рассылки</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
</{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Регистрация</h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div>
                                {{ form.as_p }}
                            </div>

                            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}body>
</html>

users/templates/users/user_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить пользователя {{ object.email }}?</p>
                            <button type="submit" class="btn btn-danger"
                                    title="УДАЛИТЬ">Удалить
                            </button>
                            <a href="{% url 'users:profile_edit' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Профиль {{ object.first_name }}</h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div>
                                {{ form.as_p }}
                            </div>
                            <button type="submit" class="btn btn-primary">Обновить данные</button>
                        </div>

                        <div class="card-footer">
                            <a href="{% url 'users:profile_delete' object.pk %}" class="btn btn-danger">Удалить
                                аккаунт</a>
                        </div>

                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row text-center">
        <h1>Список пользователей</h1>
    </div>

    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-sm-5">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h6 class="my-0 font-weight-normal">Email пользователя: {{ object.email }}</h6>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li><h6>Данные пользователя:</h6></li>
                            Имя: {{ object.first_name }}<br/>
                            Фамилия: {{ object.last_name }}<br/>
                            {% if object.is_active %}
                                Активен
                            {% else %}
                                Отключен
                            {% endif %}
                        </ul>
                        {% if object.is_active %}
                            <a href="{% url 'users:user_disable' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Отключить пользователя</a>
                        {% else %}
                            <a href="{% url 'users:user_disable' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Активировать пользователя</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/verification.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Подтверждение регистрации</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Верификация аккаунта</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            <p>Введите код, указанный в письме на почте</p>
                            {% csrf_token %}
                            <div class="mb-3">
                                <input type="text" name="verify_code" class="form-control" id="verify_code"
                                       placeholder="Введите код из письма" required>
                            </div>

                            <input type="submit" class="btn btn-success">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}