blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

mailing_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('client/', include('client.urls', namespace='client')),
                  path('mailing/', include('newletter.urls', namespace='newletter')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newletter/urls.py
from django.urls import path

from newletter.apps import NewletterConfig
from newletter.views import MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, \
    MessageDeleteView, MailingLogsListView, SettingsListView, SettingCreateView, SettingUpdateView, SettingDeleteView

app_name = NewletterConfig.name

urlpatterns = [
    path('list/', MessageListView.as_view(), name='message_list'),
    path('list/detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('list/create/', MessageCreateView.as_view(), name='message_create'),
    path('list/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('list/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('logs/', MailingLogsListView.as_view(), name='report_list'),
    path('settings/list', SettingsListView.as_view(), name='setting_list'),
    path('settings/create', SettingCreateView.as_view(), name='setting_create'),
    path('settings/update/<int:pk>', SettingUpdateView.as_view(), name='setting_update'),
    path('settings/delete/<int:pk>', SettingDeleteView.as_view(), name='setting_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, logout_view, RegisterView, UserUpdateView, UserVerifyView, \
    ManagerView, UserListView, DisableUserView, DisableMessageView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verify/<int:pk>/', UserVerifyView.as_view(), name='verification'),
    path('profile_edit/', UserUpdateView.as_view(), name='profile_edit'),
    path('profile_delete/<int:pk>/', UserDeleteView.as_view(), name='profile_delete'),
    path('manager/', ManagerView.as_view(), name='manager_profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('disable_user/<int:pk>/', DisableUserView.as_view(), name='user_disable'),
    path('disable_message/<int:pk>/', DisableMessageView.as_view(), name='message_disable'),
]

newletter/models.py
from django.conf import settings
from django.db import models

from client.models import Client
from users.models import NULLABLE


# Create your models here.
class MailingSettings(models.Model):
    send_time = models.DateTimeField(verbose_name='Время рассылки')

    frequency_choices = [
        ('Daily', 'Ежедневно'),
        ('Weekly', 'Еженедельно'),
        ('Monthly', 'Ежемесячно'),
    ]
    frequency = models.CharField(max_length=30, choices=frequency_choices, verbose_name='Регулярность')

    status_choices = [
        ('Created', 'Создана'),
        ('Started', 'Запущена'),
        ('Completed', 'Завершена'),
    ]
    status = models.CharField(max_length=30, choices=status_choices, verbose_name='статус рассылки')

    def __str__(self):
        return f'{self.send_time} - {self.frequency}'

    class Meta:
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'


class Message(models.Model):
    client = models.ManyToManyField(Client, verbose_name='Клиент')
    mailing_settings = models.ForeignKey(MailingSettings, on_delete=models.SET_NULL, null=True,
                                         verbose_name='Настройки')

    title = models.CharField(max_length=255, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Текст письма')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец')
    is_active = models.BooleanField(default=True, verbose_name='Активна?')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingLogs(models.Model):
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, null=True, verbose_name='Рассылка')
    datetime_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')
    status = models.CharField(max_length=30, verbose_name='Статус')
    server_response = models.TextField(**NULLABLE, verbose_name='Ответ сервиса')

    def __str__(self):
        return f'{self.status} в {self.datetime_attempt}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

newletter/forms.py
from django import forms

from newletter.models import Message
from newletter.validators import validate_mail


class MessageForm(forms.ModelForm):
    title = forms.CharField(validators=[validate_mail],
                            label='Название рассылки',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Название',
                                }
                            ))

    body = forms.CharField(validators=[validate_mail],
                           label='Содержимое рассылки',
                           widget=forms.Textarea(
                               attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Содержимое рассылки',
                               }
                           ))

    class Meta:
        model = Message
        fields = ('client', 'title', 'body', 'mailing_settings',)
        widgets = {
            'client': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'mailing_settings': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'client': 'Выберите клиентов',
            'mailing_settings': 'Выберите настройки',
        }

newletter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from newletter.forms import MessageForm
from newletter.models import Message, MailingLogs, MailingSettings


# Create your views here.
class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    ordering = ('title',)
    extra_context = {
        'title': 'Список рассылок'
    }


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    extra_context = {
        'title': 'Просмотр рассылки'
    }


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('newletter:message_list')

    extra_context = {
        'title': 'Создание рассылки'
    }

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Message
    form_class = MessageForm

    extra_context = {
        'title': 'Редактирование рассылки'
    }

    def get_success_url(self):
        return reverse('newletter:message_detail', args=[self.kwargs.get('pk')])

    def test_func(self):
        return self.request.user == self.get_object().owner or self.request.user.is_superuser


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('newletter:message_list')

    extra_context = {
        'title': 'Удаление рассылки'
    }

    def test_func(self):
        return self.request.user == self.get_object().owner or self.request.user.is_superuser


class MailingLogsListView(LoginRequiredMixin, ListView):
    model = MailingLogs
    template_name = "newletter/logs_list.html"
    extra_context = {
        'title': 'Отчет рассылок'
    }

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return MailingLogs.objects.all()
        else:
            return MailingLogs.objects.filter(message__owner=self.request.user)


class SettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings
    template_name = "newletter/settings_list.html"
    extra_context = {
        'title': 'Настройки рассылок'
    }


class SettingCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    template_name = "newletter/settings_form.html"

    success_url = reverse_lazy('newletter:setting_list')
    fields = ('send_time', 'frequency', 'status',)

    extra_context = {
        'title': 'Создание Настройки'
    }


class SettingUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    template_name = "newletter/settings_form.html"
    success_url = reverse_lazy('newletter:setting_list')
    fields = ('send_time', 'frequency', 'status',)

    extra_context = {
        'title': 'Редактирование Настройки'
    }


class SettingDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    template_name = "newletter/settings_confirm_delete.html"
    success_url = reverse_lazy('newletter:message_list')

    extra_context = {
        'title': 'Удаление настройки'
    }

newletter/templates/newletter/logs_list.html
{% extends 'main/base.html' %}

{% block content %}
    <table class="table table-hover">
        <caption class="caption-top">Логи рассылок</caption>
        <thead class="table-secondary">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Рассылка</th>
            <th scope="col">Дата и время попытки</th>
            <th scope="col">Статус попытки</th>
            <th scope="col">Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ object.pk }}</th>
                <td>
                    {% if object.message %}
                        <a href="{% url 'newletter:message_detail' object.message.pk %}"
                           class="custom-link">{{ object.message }}</a>
                    {% else %}
                        <strong style="color:darkred">Удалено</strong>
                    {% endif %}
                </td>
                <td>{{ object.datetime_attempt }}</td>
                <td style="color: {% if object.status == 'Ошибка отправки' %}red{% elif object.status == 'Успешно отправлено' %}green{% else %}black{% endif %}">
                    {{ object.status }}
                </td>
                <td>{{ object.server_response }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

newletter/templates/newletter/message_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить рассылку {{ object.title }}?</p>
                        <button type="submit" class="btn btn-danger"
                                title="Полностью удалить">Удалить
                        </button>
                        <a href="{% url 'newletter:message_detail' object.pk %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newletter/templates/newletter/message_detail.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">

            {% if object.owner == user or user.is_superuser or user.is_staff %}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                {{ object.title|title }}
                            </h3>
                        </div>
                        <div class="card-body">
                            <p>
                                <strong>Содержимое рассылки:</strong><br/>
                                {{ object.body }}
                            </p>
                            <p>
                                <strong>Рассылается для:</strong>
                                {% for client_object in object.client.all %}<br/>
                                    {{ client_object }}
                                {% endfor %}
                            </p>
                            <p>
                                <strong>Настройки рассылки:</strong><br/>
                                {{ object.mailing_settings }}
                            </p>
                            <p>
                                <strong>Владелец рассылки:</strong><br/>
                                {{ object.owner }}
                            </p>
                            <p>
                                <strong>Признак активности:</strong><br/>
                                {% if object.is_active %}
                                    <span class="active-status active">Активна</span>
                                {% else %}
                                    <span class="active-status inactive">Не активна</span>
                                {% endif %}
                            </p>
                        </div>

                        <div class="card bg-light">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    {% if object.owner == user or user.is_superuser %}
                                        <a href="{% url 'newletter:message_update' object.pk %}" type="button"
                                           class="btn btn-outline-secondary">Редактировать</a>
                                        <a href="{% url 'newletter:message_delete' object.pk %}" type="button"
                                           class="btn btn-outline-danger">Удалить</a>
                                    {% endif %}
                                    {% if user.is_staff %}
                                        {% if object.is_active %}
                                            <a href="{% url 'users:message_disable' object.pk %}" type="button"
                                               class="btn btn-outline-danger">Отключить рассылку</a>
                                        {% else %}
                                            <a href="{% url 'users:message_disable' object.pk %}" type="button"
                                               class="btn btn-outline-success">Включить рассылку</a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% else %}
                <h3>Нет прав для просмотра</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

newletter/templates/newletter/message_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-lg-5 col-md-6 col-sm-12 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if object %}
                    <h5 class="my-0 font-weight-normal">Редактировать рассылку</h5>
                {% else %}
                    <h5 class="my-0 font-weight-normal">Создать рассылку</h5>
                {% endif %}
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if object %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-light">Редактировать
                        </button>
                    {% else %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-light">Создать</button>
                    {% endif %}
                </form>

            </div>
        </div>
    </div>
{% endblock %}

newletter/templates/newletter/message_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row text-center mb-2">
        {% if user.is_superuser or user.is_staff %}
            <h1>Все рассылки</h1>
        {% else %}
            <h1>Ваши рассылки</h1>
        {% endif %}
    </div>

    <div class="row text-center">

        {% for object in object_list %}
            {% if object.owner == user or user.is_superuser or user.is_staff %}
                <div class="col-sm-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h5 class="my-0 font-weight-normal">{{ object.title|title }}</h5>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'newletter:message_detail' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Подробнее...</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        <div class="col-sm-5">
            <div class="card mb-3 box-shadow">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">Место для вашей рассылки</h5>
                </div>
                <div class="card-body">
                    <a href="{% url 'newletter:message_create' %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Создать рассылку</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newletter/templates/newletter/settings_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить настройку на время {{ object.send_time }} и регулярностью {{ object.frequency }}?</p>
                        <button type="submit" class="btn btn-danger"
                                title="Полностью удалить">Удалить
                        </button>
                        <a href="{% url 'newletter:setting_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newletter/templates/newletter/settings_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.send_time.label }}">Время рассылки</label><br/>
                            {{ form.send_time }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.frequency.label }}">Регулярность</label><br/>
                            {{ form.frequency }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.status.label }}">Статус</label><br/>
                            {{ form.status }}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                                Сохранить настройку
                            {% else %}
                                Создать настройку
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newletter/templates/newletter/settings_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
        <p class="lead">Настройки для рассылок</p>

    </div>
        <div class="col-4 mb-5">
            <a class="btn btn-outline-primary" href="{% url 'newletter:setting_create' %}">Добавить настройку для рассылки</a>
        </div>

    <div class="d-flex flex-wrap">
        {% for object in object_list %}
            <div class="card m-2" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Время рассылки: {{ object.send_time }}</h5>
                    <p class="card-text">Регулярность: {{ object.frequency }}</p>
                    <p class="card-text">Статус: {{ object.status }}</p>
                    {% if content_manager %}<br/>
                        <a href="{% url 'newletter:setting_update' object.pk %}" type="button" class="btn btn-secondary">Редактировать</a>
                        <a href="{% url 'newletter:setting_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}